name: 'dev_build'
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ['1.3.1', '1.4.2', '1.4.7', '1.5.2', '1.6.4', '1.7.2', '1.7.4', '1.7.10', '1.8.0', '1.8.3-15w14a', '1.8.9', '1.9.4', '1.10.2', '1.11.2', '1.12', '1.12.2', '1.13.2', '1.14.4', '1.15.2', '1.16.0-20w14infinite', '1.16.1', '1.16.5', '1.17.0', '1.17.1', '1.18.1', '1.18.2', '1.18.2-22w13oneblockatatime', '1.19.2', '1.19.4', '1.20-23w13a_or_b', '1.20.1', '1.20.4', '1.20.5-24w14potato', '1.20.6', '1.21']
    steps:
      - name: Checkout ${{ matrix.branch }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ matrix.branch }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'


      - name: Make gradlew executable - ${{ matrix.branch }}
        run: chmod +x ./gradlew
      - name: Build artifacts - ${{ matrix.branch }}
        run: ./gradlew build


      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs/*.jar